version: "2"
services:
  lb:
    image: rancher/lb-service-haproxy:v0.9.14
    expose:
      - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.agent_service.drain_provider: "true"
      io.rancher.container.create_agent: "true"
      io.rancher.lb_service.target: any
      web.http: "true"
  web:
    image: $WEB_IMAGE
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      web.container.target: $CI_PROJECT_PATH_SLUG.$CI_ENV
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
      NGINX_START: true
    command: ["yarn", "start"]
  se:
    image: getmeili/meilisearch:v1.6.0
    labels:
      io.rancher.container.pull_image: always
      se.container.target: $CI_PROJECT_PATH_SLUG.$CI_ENV
    environment:
      - MEILI_MASTER_KEY
      - MEILI_ENV
      - MEILI_HTTP_ADDR=0.0.0.0:80
    volumes:
      - /data/nfs/volumes/$CI_PROJECT_PATH_SLUG/meili_data:/meili_data
